add_newline = false
command_timeout = 1000
format = """$directory$git_branch$git_status
[❯](bright-green) """

[character]
success_symbol = ''
error_symbol = ''

[directory]
home_symbol = '~'
truncation_length = 0
truncate_to_repo = false
format = '[$path]($style)$read_only '
style = 'bold cyan'

[git_branch]
symbol = ' '
format = 'on [$symbol$branch]($style)'
style = 'bold bright-red'

[git_status]
format = '([ $all_status$ahead_behind](bold white))'
conflicted = '[=](bold bright-red)'
untracked = '[?](bold bright-red)'
stashed = '[^](bold bright-green)'
modified = '[!](bold bright-yellow)'
staged = '[+](bold bright-green)'
renamed = '[»](bold bright-green)'
deleted = '[✘](bold bright-red)'
ahead = '>'
diverged = '<>'
behind = '<'

[docker_context]
disabled = true

[python]
disabled = true

[nodejs]
disabled = true
